# Generated by Django 3.0 on 2020-05-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_auto_20200516_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
